"""Attestation Gate.

Records the operator attestation that authorised use of any real-people /
in-copyright source. The Packager stamps the synthetic-evidence disclaimer
into per-artifact metadata; this gate persists the attestation text into
the sealed pack.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime

SYNTHETIC_EVIDENCE_DISCLAIMER = (
    "SYNTHETIC EVIDENCE — artifact generated by Evidence Factory; not a real disclosure."
)


@dataclass(frozen=True)
class Attestation:
    checked: bool
    attested_at: datetime
    operator_label: str

    def as_text(self) -> str:
        return (
            f"Operator '{self.operator_label}' attested authorised use at "
            f"{self.attested_at.isoformat()}."
        )


@dataclass(frozen=True)
class CaseContext:
    """Per-run context the Attestation Gate seals after operator attestation.

    Carries the operator attestation plus the synthetic-evidence watermark the
    Packager stamps into every artifact and the top-level ``MANIFEST.txt``.
    """

    attestation: Attestation
    synthetic_evidence: bool
    disclaimer: str


class AttestationRequired(Exception):
    pass


def gate(
    checked: bool,
    *,
    operator_label: str = "anonymous-operator",
    disclaimer: str = SYNTHETIC_EVIDENCE_DISCLAIMER,
) -> CaseContext:
    """Record the operator attestation and set the synthetic-evidence
    disclaimer field on the case context.

    Raises ``AttestationRequired`` unless the operator has attested authorised
    use of any real-people / in-copyright source.
    """
    if not checked:
        raise AttestationRequired("operator must attest authorised use before generation")
    attestation = Attestation(
        checked=True,
        attested_at=datetime.now(UTC),
        operator_label=operator_label,
    )
    return CaseContext(
        attestation=attestation,
        synthetic_evidence=True,
        disclaimer=disclaimer,
    )
