"""Attestation Gate.

Records the operator attestation that authorised use of any real-people /
in-copyright source. The Packager stamps the synthetic-evidence disclaimer
into per-artifact metadata; this gate persists the attestation text into
the sealed pack.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime

SYNTHETIC_EVIDENCE_DISCLAIMER = (
    "SYNTHETIC EVIDENCE — artifact generated by Evidence Factory; not a real disclosure."
)


@dataclass(frozen=True)
class Attestation:
    checked: bool
    attested_at: datetime
    operator_label: str

    def as_text(self) -> str:
        return (
            f"Operator '{self.operator_label}' attested authorised use at "
            f"{self.attested_at.isoformat()}."
        )


class AttestationRequired(Exception):
    pass


def gate(checked: bool, *, operator_label: str = "anonymous-operator") -> Attestation:
    if not checked:
        raise AttestationRequired("operator must attest authorised use before generation")
    return Attestation(
        checked=True,
        attested_at=datetime.now(UTC),
        operator_label=operator_label,
    )
